import arrowDown from "@iconify-icons/ri/arrow-down-line";
import arrowDownCircle from "@iconify-icons/ri/arrow-down-circle-line";
import arrowDownDouble from "@iconify-icons/ri/arrow-down-double-line";
import arrowDownS from "@iconify-icons/ri/arrow-down-s-line";
import arrowDropDown from "@iconify-icons/ri/arrow-drop-down-line";
import arrowDropLeft from "@iconify-icons/ri/arrow-drop-left-line";
import arrowDropRight from "@iconify-icons/ri/arrow-drop-right-line";
import arrowDropUp from "@iconify-icons/ri/arrow-drop-up-line";
import arrowGoBack from "@iconify-icons/ri/arrow-go-back-line";
import arrowGoForward from "@iconify-icons/ri/arrow-go-forward-line";
import arrowLeft from "@iconify-icons/ri/arrow-left-line";
import arrowLeftCircle from "@iconify-icons/ri/arrow-left-circle-line";
import arrowLeftDouble from "@iconify-icons/ri/arrow-left-double-line";
import arrowLeftDown from "@iconify-icons/ri/arrow-left-down-line";
import arrowLeftRight from "@iconify-icons/ri/arrow-left-right-line";
import arrowLeftS from "@iconify-icons/ri/arrow-left-s-line";
import arrowLeftUp from "@iconify-icons/ri/arrow-left-up-line";
import arrowRight from "@iconify-icons/ri/arrow-right-line";
import arrowRightCircle from "@iconify-icons/ri/arrow-right-circle-line";
import arrowRightDouble from "@iconify-icons/ri/arrow-right-double-line";
import arrowRightDown from "@iconify-icons/ri/arrow-right-down-line";
import arrowRightS from "@iconify-icons/ri/arrow-right-s-line";
import arrowRightUp from "@iconify-icons/ri/arrow-right-up-line";
import arrowTurnBack from "@iconify-icons/ri/arrow-turn-back-line";
import arrowTurnForward from "@iconify-icons/ri/arrow-turn-forward-line";
import arrowUp from "@iconify-icons/ri/arrow-up-line";
import arrowUpCircle from "@iconify-icons/ri/arrow-up-circle-line";
import arrowUpDouble from "@iconify-icons/ri/arrow-up-double-line";
import arrowUpDown from "@iconify-icons/ri/arrow-up-down-line";
import arrowUpS from "@iconify-icons/ri/arrow-up-s-line";
import { createIcon } from "./icon";

export const ArrowDownIcon = createIcon(arrowDown);
export const ArrowDownCircleIcon = createIcon(arrowDownCircle);
export const ArrowDownDoubleIcon = createIcon(arrowDownDouble);
export const ArrowDownSIcon = createIcon(arrowDownS);
export const ArrowDropDownIcon = createIcon(arrowDropDown);
export const ArrowDropLeftIcon = createIcon(arrowDropLeft);
export const ArrowDropRightIcon = createIcon(arrowDropRight);
export const ArrowDropUpIcon = createIcon(arrowDropUp);
export const ArrowGoBackIcon = createIcon(arrowGoBack);
export const ArrowGoForwardIcon = createIcon(arrowGoForward);
export const ArrowLeftIcon = createIcon(arrowLeft);
export const ArrowLeftCircleIcon = createIcon(arrowLeftCircle);
export const ArrowLeftDoubleIcon = createIcon(arrowLeftDouble);
export const ArrowLeftDownIcon = createIcon(arrowLeftDown);
export const ArrowLeftRightIcon = createIcon(arrowLeftRight);
export const ArrowLeftSIcon = createIcon(arrowLeftS);
export const ArrowLeftUpIcon = createIcon(arrowLeftUp);
export const ArrowRightIcon = createIcon(arrowRight);
export const ArrowRightCircleIcon = createIcon(arrowRightCircle);
export const ArrowRightDoubleIcon = createIcon(arrowRightDouble);
export const ArrowRightDownIcon = createIcon(arrowRightDown);
export const ArrowRightSIcon = createIcon(arrowRightS);
export const ArrowRightUpIcon = createIcon(arrowRightUp);
export const ArrowTurnBackIcon = createIcon(arrowTurnBack);
export const ArrowTurnForwardIcon = createIcon(arrowTurnForward);
export const ArrowUpIcon = createIcon(arrowUp);
export const ArrowUpCircleIcon = createIcon(arrowUpCircle);
export const ArrowUpDoubleIcon = createIcon(arrowUpDouble);
export const ArrowUpDownIcon = createIcon(arrowUpDown);
export const ArrowUpSIcon = createIcon(arrowUpS);
