/** @jsxImportSource @nataliebasille/preview-jsx-runtime */

export default {
  title: 'List',
  description:
    'Structured lists with optional interactive rows, unordered markers, or decimal counters. Mark each child item with data-slot="item" so the list component can apply spacing, markers, and row states.',
  atAGlance: (
    <ui-div className="md:grid-cols-3 grid w-full gap-4">
      {plainList('list/primary')}
      {discList('list-disc/secondary')}
      {decimalList('list-decimal/accent')}
    </ui-div>
  ),
  components: {
    list: {
      name: 'List',
      description:
        'Applies base list reset, vertical spacing, and interactive item states. Use the optional palette modifier to tune hover and active colors.',
      showcases: [
        {
          title: 'Interactive',
          description:
            'Use the base list class for action lists, navigation rows, or selectable option groups.',
          content: plainList('list/primary'),
        },
        {
          title: 'Palettes',
          description: 'The base list supports tone palettes for hover and active row states.',
          content: paletteShowcase(),
        },
      ],
    },
    'list@variant': {
      name: 'Marker Style',
      description:
        'Switches the list marker treatment. Use list-disc for unordered content and list-decimal for ordered steps.',
      showcases: [
        {
          title: 'Disc',
          description:
            'Use list-disc for unordered content where rows should read as static list items.',
          content: discList('list-disc/secondary'),
        },
        {
          title: 'Decimal',
          description:
            'Use list-decimal for ordered sequences. Counters are generated by the component.',
          content: decimalList('list-decimal/accent'),
        },
      ],
    },
  },
  slots: {
    title: 'Item Slot',
    description:
      'Add data-slot="item" to direct children so list styles can target each row or marker item.',
    showcases: [
      {
        title: 'Slot Markup',
        description:
          'The item slot keeps the child markup explicit while allowing the builder to document the selector.',
        content: slotShowcase(),
      },
    ],
  },
  cssvars: {
    '--item-marker-font-size': 'Font size for generated disc and decimal markers.',
    '--item-marker-top': 'Vertical offset for generated disc and decimal markers.',
  },
} satisfies Documentation<
  typeof import('../../../../../packages/core-v2/src/tailwind/components/list.css.ts').default
>

function plainList(className: string) {
  return (
    <ul className={className}>
      <li data-slot="item">Profile</li>
      <li data-slot="item" className="active">
        Security
      </li>
      <li data-slot="item">Notifications</li>
    </ul>
  )
}

function discList(className: string) {
  return (
    <ul className={className}>
      <li data-slot="item">Design tokens</li>
      <li data-slot="item">Component builders</li>
      <li data-slot="item">Generated utilities</li>
    </ul>
  )
}

function decimalList(className: string) {
  return (
    <ol className={className}>
      <li data-slot="item">Choose a component class</li>
      <li data-slot="item">Add data-slot="item" to each child</li>
      <li data-slot="item">Pick disc or decimal when needed</li>
    </ol>
  )
}

function paletteShowcase() {
  return (
    <ui-div className="md:grid-cols-2 grid w-full gap-4">
      {plainList('list/primary')}
      {plainList('list/accent')}
    </ui-div>
  )
}

function slotShowcase() {
  return (
    <ul className="list/primary">
      <li data-slot="item">First item</li>
      <li data-slot="item">Second item</li>
      <li data-slot="item">Third item</li>
    </ul>
  )
}
